# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/danny/class/labs/lab11/hardware/bd/webserver_fwm/ip/webserver_fwm_processing_system7_0_0/webserver_fwm_processing_system7_0_0.xci
# IP: The module: 'webserver_fwm_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/danny/class/labs/lab11/hardware/bd/webserver_fwm/ip/webserver_fwm_processing_system7_0_0/webserver_fwm_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'webserver_fwm_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/danny/class/labs/lab11/hardware/bd/webserver_fwm/ip/webserver_fwm_processing_system7_0_0/webserver_fwm_processing_system7_0_0.xci
# IP: The module: 'webserver_fwm_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/danny/class/labs/lab11/hardware/bd/webserver_fwm/ip/webserver_fwm_processing_system7_0_0/webserver_fwm_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'webserver_fwm_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
