# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: /home/danny/class/labs/lab11/hardware/bd/webserver_fwm/webserver_fwm.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==webserver_fwm || ORIG_REF_NAME==webserver_fwm} -quiet] -quiet

# IP: /home/danny/class/labs/lab11/hardware/bd/webserver_fwm/ip/webserver_fwm_processing_system7_0_0/webserver_fwm_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==webserver_fwm_processing_system7_0_0 || ORIG_REF_NAME==webserver_fwm_processing_system7_0_0} -quiet] -quiet

# XDC: /home/danny/class/labs/lab11/hardware/bd/webserver_fwm/webserver_fwm_ooc.xdc
